# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RRvROaWc5vpPcCJ_3EpB9lU0i8vIgez
"""

import pandas as pd
import numpy as np
import patsy as pt

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

training = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv")

#training = training.drop('DateTime', axis = 'columns')
training['DateTime'] = pd.to_datetime(training['DateTime'])

training["day"] = training['DateTime'].map(lambda x: x.day)
training["month"] = training['DateTime'].map(lambda x: x.month)
training["year"] = training['DateTime'].map(lambda x: x.year)
training["hour"] = training['DateTime'].map(lambda x: x.hour)

training = training.drop('id', axis = 'columns')
training = training.drop('DateTime', axis = 'columns')

training

# Commented out IPython magic to ensure Python compatibility.
model = DecisionTreeClassifier()

Y = training['meal']
X = training.drop('meal', axis = 'columns')

x, xt, y, yt = train_test_split(X, Y, test_size=0.33, random_state=42)

modelFit = model.fit(x,y)

print("\n\nIn-sample accuracy: %s%%\n\n"
#  % str(round(100*accuracy_score(y, model.predict(x)), 2)))

pred = model.predict(X)